apiVersion: v1
kind: Service
metadata:
  name: numspot-frontend
  labels:
    app: numspot-frontend
spec:
  type: ClusterIP
  selector:
    app: numspot-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
